"""Detailed plots for one complex market opening."""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime
from pathlib import Path

from ..errors import PlottingError
from ..market_models import MarketClearingResult
from .common import (
    _ENERGY_TOLERANCE_MWH,
    _OPENING_PLOT_FILENAMES,
    _annotate_no_supply,
    _save_figure,
)


def _select_opening_results(
    results: tuple[MarketClearingResult, ...],
    requested_opening_time: datetime | None,
) -> tuple[MarketClearingResult, ...]:
    """Return all products belonging to the requested or earliest opening."""

    first = results[0]
    opening_time = requested_opening_time or first.opening_time
    if opening_time is None:
        return (first,)
    selected = tuple(
        market for market in results if market.opening_time == opening_time
    )
    if not selected:
        raise PlottingError(
            "No cleared market opening exists at "
            f"{opening_time.isoformat(sep=' ', timespec='minutes')}."
        )
    return selected


def _remove_stale_opening_plots(
    openings_directory: Path,
    *,
    keep: Path | None = None,
) -> None:
    """Remove only detailed-opening PNGs generated by earlier plot runs."""

    if not openings_directory.is_dir():
        return
    for candidate in openings_directory.iterdir():
        if not candidate.is_dir() or candidate == keep:
            continue
        for filename in _OPENING_PLOT_FILENAMES:
            (candidate / filename).unlink(missing_ok=True)
        try:
            candidate.rmdir()
        except OSError:
            # Preserve directories containing files not owned by this renderer.
            pass
    if keep is None:
        try:
            openings_directory.rmdir()
        except OSError:
            pass


def _plot_opening_dispatch(
    pyplot, dates, results, unit_colors, path: Path
) -> Path:
    """Plot prices and accepted unit dispatch for one complete market opening."""

    results = tuple(sorted(results, key=lambda market: market.delivery_start))
    times = [market.delivery_start for market in results]
    prices = [market.clearing_price_eur_per_mwh for market in results]
    unit_names = sorted(
        {
            cleared.offer.unit_name
            for market in results
            for cleared in market.offers
        }
    )
    power_by_unit = {name: [] for name in unit_names}
    submitted_demand: list[float] = []
    cleared_demand: list[float] = []
    inelastic_demand: list[float] = []

    for market in results:
        accepted_power: dict[str, float] = defaultdict(float)
        for cleared in market.offers:
            accepted_power[cleared.offer.unit_name] += cleared.accepted_power_mw
        for name in unit_names:
            power_by_unit[name].append(accepted_power.get(name, 0.0))
        submitted_demand.append(market.requested_demand_power_mw)
        cleared_demand.append(market.cleared_power_mw)
        inelastic_demand.append(
            market.requested_inelastic_demand_mwh / market.duration_hours
        )

    opening_time = results[0].opening_time or results[0].delivery_start
    figure, (price_axis, dispatch_axis) = pyplot.subplots(
        2,
        1,
        figsize=(16, 9),
        sharex=True,
        gridspec_kw={"height_ratios": (1, 1.7)},
    )
    product_word = "product" if len(results) == 1 else "products"
    price_axis.set_title(
        f"Market opening {opening_time:%Y-%m-%d %H:%M} — "
        f"{len(results)} {product_word}"
    )
    price_axis.set_ylabel("Price (EUR/MWh)")
    price_axis.grid(axis="y", alpha=0.25)

    if len(results) == 1:
        _plot_single_product_opening(
            price_axis,
            dispatch_axis,
            results[0],
            prices[0],
            unit_names,
            power_by_unit,
            submitted_demand[0],
            cleared_demand[0],
            inelastic_demand[0],
            unit_colors,
        )
    else:
        price_axis.step(
            times,
            prices,
            where="mid",
            color="#2F5597",
            linewidth=1.8,
            label="Hourly uniform price",
        )
        if unit_names:
            dispatch_axis.stackplot(
                times,
                *(power_by_unit[name] for name in unit_names),
                labels=unit_names,
                colors=[unit_colors[name] for name in unit_names],
                alpha=0.78,
                step="mid",
            )
        dispatch_axis.step(
            times,
            cleared_demand,
            where="mid",
            color="#111111",
            linewidth=1.4,
            label="Cleared demand",
            zorder=4,
        )
        dispatch_axis.step(
            times,
            submitted_demand,
            where="mid",
            color="#7F7F7F",
            linewidth=1.0,
            linestyle=":",
            label="All submitted demand",
            zorder=4,
        )
        dispatch_axis.step(
            times,
            inelastic_demand,
            where="mid",
            color="#E45756",
            linewidth=1.1,
            linestyle="--",
            label="Inelastic load",
            zorder=4,
        )
        interval = max(1, len(times) // 12)
        dispatch_axis.xaxis.set_major_locator(dates.HourLocator(interval=interval))
        dispatch_axis.xaxis.set_major_formatter(dates.DateFormatter("%b %d\n%H:%M"))
        dispatch_axis.margins(x=0)

    if not unit_names:
        if len(results) == 1:
            dispatch_axis.hlines(
                0.0,
                -0.42,
                0.42,
                color="#4C78A8",
                linewidth=1.2,
                label="Accepted supply (0 MW)",
                zorder=3,
            )
        else:
            dispatch_axis.plot(
                times,
                [0.0] * len(times),
                color="#4C78A8",
                linewidth=1.2,
                label="Accepted supply (0 MW)",
                zorder=3,
            )
        _annotate_no_supply(dispatch_axis)
        dispatch_axis.set_ylim(bottom=0.0)
    price_axis.legend(loc="upper right")
    dispatch_axis.set_ylabel("Power (MW)")
    dispatch_axis.set_xlabel("Delivery start")
    dispatch_axis.grid(axis="y", alpha=0.25)
    dispatch_axis.legend(loc="upper left", ncol=min(4, len(unit_names) + 2))
    figure.tight_layout()
    return _save_figure(pyplot, figure, path)


def _plot_single_product_opening(
    price_axis,
    dispatch_axis,
    market,
    price,
    unit_names,
    power_by_unit,
    submitted_demand,
    cleared_demand,
    inelastic_demand,
    unit_colors,
) -> None:
    """Use bars when a market opening contains only one delivery product."""

    price_bars = price_axis.bar(
        [0],
        [price],
        width=0.55,
        color="#2F5597",
        label="Uniform price",
    )
    price_axis.bar_label(
        price_bars,
        labels=[f"{price:,.2f}"],
        padding=4,
        fontsize=9,
    )

    bottom = 0.0
    for name in unit_names:
        accepted_power = power_by_unit[name][0]
        if accepted_power <= _ENERGY_TOLERANCE_MWH:
            continue
        dispatch_axis.bar(
            [0],
            [accepted_power],
            width=0.55,
            bottom=bottom,
            color=unit_colors[name],
            alpha=0.78,
            label=name,
        )
        bottom += accepted_power

    dispatch_axis.hlines(
        cleared_demand,
        -0.42,
        0.42,
        color="#111111",
        linewidth=1.5,
        label="Cleared demand",
        zorder=4,
    )
    dispatch_axis.hlines(
        submitted_demand,
        -0.42,
        0.42,
        color="#7F7F7F",
        linewidth=1.0,
        linestyle=":",
        label="All submitted demand",
        zorder=4,
    )
    dispatch_axis.hlines(
        inelastic_demand,
        -0.42,
        0.42,
        color="#E45756",
        linewidth=1.2,
        linestyle="--",
        label="Inelastic load",
        zorder=4,
    )
    dispatch_axis.set_xlim(-0.7, 0.7)
    dispatch_axis.set_xticks([0])
    dispatch_axis.set_xticklabels([market.delivery_start.strftime("%b %d\n%H:%M")])


def _plot_offer_acceptance(pyplot, results, path: Path) -> Path:
    """Render accepted/submitted ratios for supply offers and demand bids."""

    results = tuple(sorted(results, key=lambda market: market.delivery_start))
    bid_order = {"BB": 0, "LB": 1, "SB": 2}
    row_keys = sorted(
        {
            (
                "Supply",
                cleared.offer.unit_name,
                cleared.offer.bid_type,
                cleared.offer.offer_segment,
            )
            for market in results
            for cleared in market.offers
        }
        | {
            (
                "Demand",
                cleared.bid.unit_name,
                cleared.bid.bid_type,
                cleared.bid.demand_type or "",
            )
            for market in results
            for cleared in market.demand_bids
        },
        key=lambda key: (
            0 if key[0] == "Supply" else 1,
            key[1],
            bid_order.get(key[2], 99),
            key[2],
            key[3],
        ),
    )
    opening_time = results[0].opening_time or results[0].delivery_start
    if not row_keys:
        figure, axis = pyplot.subplots(figsize=(9, 5))
        axis.set_title(f"Order acceptance — opening {opening_time:%Y-%m-%d %H:%M}")
        _annotate_no_supply(axis, "No orders submitted for this opening")
        axis.set_axis_off()
        figure.tight_layout()
        return _save_figure(pyplot, figure, path)

    matrix: list[list[float]] = []
    for side, unit_name, order_type, segment in row_keys:
        row: list[float] = []
        for market in results:
            if side == "Supply":
                matching_supply = [
                    cleared
                    for cleared in market.offers
                    if (
                        cleared.offer.unit_name,
                        cleared.offer.bid_type,
                        cleared.offer.offer_segment,
                    )
                    == (unit_name, order_type, segment)
                ]
                submitted = sum(
                    item.offer.offered_energy_mwh for item in matching_supply
                )
                accepted = sum(
                    item.accepted_energy_mwh for item in matching_supply
                )
            else:
                matching_demand = [
                    cleared
                    for cleared in market.demand_bids
                    if (
                        cleared.bid.unit_name,
                        cleared.bid.bid_type,
                        cleared.bid.demand_type,
                    )
                    == (unit_name, order_type, segment)
                ]
                submitted = sum(
                    item.bid.volume_mwh for item in matching_demand
                )
                accepted = sum(
                    item.accepted_energy_mwh for item in matching_demand
                )
            row.append(
                accepted / submitted
                if submitted > _ENERGY_TOLERANCE_MWH
                else float("nan")
            )
        matrix.append(row)

    figure_width = max(9, len(results) * 0.55)
    figure, axis = pyplot.subplots(
        figsize=(figure_width, max(5, len(row_keys) * 0.48 + 2))
    )
    color_map = pyplot.get_cmap("YlGnBu").copy()
    color_map.set_bad("#E5E7EB")
    image = axis.imshow(
        matrix,
        aspect="auto",
        interpolation="nearest",
        vmin=0.0,
        vmax=1.0,
        cmap=color_map,
    )
    axis.set_title(f"Order acceptance — opening {opening_time:%Y-%m-%d %H:%M}")
    axis.set_xlabel("Delivery start")
    axis.set_ylabel("Side · unit · order type · segment")
    axis.set_xticks(range(len(results)))
    axis.set_xticklabels(
        [market.delivery_start.strftime("%m-%d\n%H:%M") for market in results],
        rotation=45,
        ha="right",
    )
    axis.set_yticks(range(len(row_keys)))
    axis.set_yticklabels(
        [
            f"{side} · {unit} · {order_type} · {segment}"
            for side, unit, order_type, segment in row_keys
        ]
    )
    color_bar = figure.colorbar(image, ax=axis, pad=0.015)
    color_bar.set_label("Accepted / submitted energy")
    figure.tight_layout()
    return _save_figure(pyplot, figure, path)
